<a href="https://colab.research.google.com/github/greapis/Python_practice/blob/main/Isuan_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
import tensorflow as tf

print(tf.__version__)
print(np.__version__)

2.17.0
1.26.4


In [12]:
# xData = [1, 2, 3, 4, 5, 6, 7]
# yData = [25,000,  55,000, 75,000, 110,000, 128,000, 155,000, 180,000]

# W = tf.Variable(tf.random.uniform([1], -100, 100))
# b = tf.Variable(tf.random.uniform([1], -100, 100))
# X = xData = tf.constant(xData, dtype=tf.float32)
# Y = yData = tf.constant(yData, dtype=tf.float32)
# H = W * X + b

In [13]:
# cost = tf.reduce_mean(tf.square(H - Y))
# a = tf.Variable(0.01)
# optimizer = tf.train.GradientDescentOptimizer(a)
# train = optimizer.minimize(cost)
# init = tf.global_variables_initializer()
# sess = tf.Session()
# sess.run(init)

In [14]:
# for i in range(5001):
#   sess.run(train, feed_dict={X: xData, Y: yData})
#   if i % 500 == 0:
#     print(i, sess.run(cost, feed_dict={X: xData, Y: yData}), sess.run(W), sess.run(b))
# print (sess.run(H, feed_dict={X: [8]}))

In [15]:
import tensorflow as tf

# 데이터 준비
xData = [1, 2, 3, 4, 5, 6, 7]
yData = [25000, 55000, 75000, 110000, 128000, 155000, 180000]  # Corrected yData

# 변수 초기화
W = tf.Variable(tf.random.uniform([1], -100, 100))
b = tf.Variable(tf.random.uniform([1], -100, 100))

In [16]:
# 모델 정의
def model(X):
  # Convert X to float32 before multiplication
  return W * tf.cast(X, dtype=tf.float32) + b

# 손실 함수 정의
def compute_loss(Y_pred, Y_true):
  return tf.reduce_mean(tf.square(Y_pred - Y_true))

# 옵티마이저 정의
optimizer = tf.optimizers.SGD(learning_rate = 0.01)

In [17]:
#  학습 함수 정의
def train_step(X, Y):
  with tf.GradientTape() as tape:
    Y_pred = model(X)
    # Cast Y to float32 before calculating loss
    loss = compute_loss(Y_pred, tf.cast(Y, dtype=tf.float32))
  gradients = tape.gradient(loss, [W, b])
  optimizer.apply_gradients(zip(gradients, [W, b]))
  return loss

#  데이터셋 준비
dataset = tf.data.Dataset.from_tensor_slices((xData, yData)).batch(len(xData)) # Now xData and yData have the same length

In [18]:
# 학습
for epoch in range(1001):
  for X_batch, Y_batch in dataset:
    loss = train_step(X_batch, Y_batch)
  if epoch % 100 ==0:
    print(f'Epoch {epoch}: Loss = {loss.numpy()}, W = {W.numpy()}, b = {b.numpy()}')

Epoch 0: Loss = 13534172160.0, W = [10341.242], b = [2008.4014]
Epoch 100: Loss = 9792839.0, W = [25158.441], b = [3827.3699]
Epoch 200: Loss = 9169606.0, W = [25313.307], b = [3060.4873]
Epoch 300: Loss = 8881165.0, W = [25418.662], b = [2538.7751]
Epoch 400: Loss = 8747665.0, W = [25490.336], b = [2183.8496]
Epoch 500: Loss = 8685885.0, W = [25539.096], b = [1942.3926]
Epoch 600: Loss = 8657282.0, W = [25572.27], b = [1778.1263]
Epoch 700: Loss = 8644057.0, W = [25594.836], b = [1666.3744]
Epoch 800: Loss = 8637926.0, W = [25610.188], b = [1590.3501]
Epoch 900: Loss = 8635098.0, W = [25620.633], b = [1538.6305]
Epoch 1000: Loss = 8633783.0, W = [25627.736], b = [1503.4479]


In [19]:
import tensorflow as tf

a = tf.constant(1)
b = tf.constant(2)

c = tf.add(a, b)
# sess = tf.Session()
# sess.run(c)

c

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [20]:
import tensorflow as tf

a = tf.Variable(5)
b = tf.Variable(3)

c = tf.multiply(a, b)
# init = tf.global_variables_initializer()

print(c)

tf.Tensor(15, shape=(), dtype=int32)


In [28]:
import tensorflow as tf

input_data = [1, 2, 3, 4, 5]

# x = tf.placeholder(dtype=tf.float32)
x = tf.constant(input_data, dtype=tf.float32)
y = x + 5

# sess = tf.Session()
# sess.run(y, feed_dict={x: input})

# print(y)

print(y.numpy())

[ 6.  7.  8.  9. 10.]


In [34]:
import tensorflow as tf
import numpy as np

mathscore = [85, 99, 84, 97, 92]
englishscore = [59, 80, 84, 68, 77]

a = tf.constant(mathscore, dtype=tf.float32)
b = tf.constant(englishscore, dtype=tf.float32)

# a = tf.placeholder(dtype=tf.float32)
# b = tf.placeholder(dtype=tf.float32)

y = (a + b) / 2

# sess = tf.Session()
# sess.run(y, feed_dict={a: mathscore, b: englishscore})

print(y.numpy())

[72.  89.5 84.  82.5 84.5]
